name: benchmark

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  benchmark:
    name: benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install -e .[tests]
      - name: Run benchmarks
        run: |
          python -m pytest tests/bench.py --codspeed -vv