name: lint
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  black:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install black
        run: pip install black
      - name: Black formatting
        run: black --check .

  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install ruff
        run: pip install ruff
      - name: Ruff linting
        run: ruff check

  mypy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install mypy
        run: |
          pip install mypy
          pip install '.[cli]'
      - name: Mypy type checking
        run: mypy