name: tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests:
    name: tests
    strategy:
      fail-fast: false
      matrix:
        platform: [ "ubuntu-latest", "macos-latest", "windows-latest" ]
        python-version: [ "3.11", "3.12", "3.13" ]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install deps
        run: |
          python -m pip install -e .[tests]
      - name: Run tests
        run: |
          python -m pytest